name: tilak_mitra_mandal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.20.2
  mime: ^2.0.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Add this line

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

# Add this configuration for easy logo change
flutter_launcher_icons:
  android: "launcher_icon"
  ios: trueag
  image_path: "lib/assets/tilak.png" # Your new logo file
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/tilak.png"
  windows:
    generate: true
    image_path: "lib/assets/tilak.png"
